services:
  hello-world:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    network_mode: "host"
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8081:8080